language: cpp

os:
  - linux
compiler:
  - g++
  - clang
script:
  - cmake -DBUILD_TESTS=ON . -Bbuild && cmake --build build && ./build/tests
  - libtoolize && aclocal && autoconf && automake --add-missing && ./configure && make && ./tests

branches:
 only:
  - master
  - dev

dist: trusty
install: true

notifications:
  email: false