version: 1.0.{build}

branches:
  only:
  - master
  - dev

configuration:
- Debug

platform: Any CPU

build_script:
- ps: >-
    cmake -DBUILD_TESTS=ON . -Bbuild

    cmake --build build --config $env:CONFIGURATION
test_script:
- ps:
    $path = Join-Path "./build/" $env:CONFIGURATION
    
    cd $path

    .\tests.exe